### PR TITLE
feat: 1st mission commit by yerim

### PR DESCRIPTION
**Pull request by Yerim96**
1. Introduce your 3 rules to other
열심히 하기 , 지각 안하기, 자습 빼놓지 않고 하기
3. Get an approval from a total of 3 people.

### CODE REVIEW

**Comment by godk0012** [comment]
good!

**Review by godk0012 — APPROVED** [review]
good!

**Review by DaeyongGwon — APPROVED** [review]
good!

**Review by miraeleee — APPROVED** [review]
good

**Review by ox01220122 — APPROVED** [review]

**Pull request closed without merging**
