### PR TITLE
init : wish and 3 rules #15

### PR DESCRIPTION
**Pull request by azure-B**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Review by dpflsy25 — APPROVED** [review]
^^b

**Comment by yeooong-dev** [comment]
Good!!

**Review by ujs-joon — APPROVED** [review]
good

**Review by yeooong-dev — COMMENTED** [review]
굿굿~!

**Review by yeooong-dev — APPROVED** [review]
굿굿굿굿!

**Pull request merged**
