### PR TITLE
[ Feat ] yooni.md Create

### PR DESCRIPTION
**Pull request by sosoyoun**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Review by baekseungchan1117 — APPROVED** [review]
good

**Comment by godk0012** [comment]
good!

**Comment by DaeyongGwon** [comment]
good

**Review by dpflsy25 — APPROVED** [review]
^^b

**Comment by ox01220122** [comment]
good

**Review by ox01220122 — APPROVED** [review]
good

**Pull request merged**
